export const SHOP_MODULE = {
  SET_SHOPS: 'SET_SHOPS',
  GET_SHOPS: 'GET_SHOPS',
  SET_SHOP: 'SET_SHOP',
  GET_SHOP: 'GET_SHOP',
  CREATE_SHOP: 'CREATE_SHOP',
  UPDATE_SHOP: 'UPDATE_SHOP',
  SHOPS: 'SHOPS',
  SHOP: 'SHOP',
  DESTROY_SHOP: 'DESTROY_SHOP'
}

export const PRODUCT_MODULE = {
  SET_PRODUCTS: 'SET_PRODUCTS',
  GET_PRODUCTS: 'GET_PRODUCTS',
  SET_PRODUCT: 'SET_PRODUCT',
  GET_PRODUCT: 'GET_PRODUCT',
  PRODUCTS: 'PRODUCTS',
  PRODUCT: 'PRODUCT',
  SET_PRODUCT_STATS: 'SET_PRODUCT_STATS',
  GET_PRODUCT_STATS: 'GET_PRODUCT_STATS',
  PRODUCT_STATS: 'PRODUCT_STATS',
  GET_PRODUCTS_REPORT_STOCK: 'GET_PRODUCTS_REPORT_STOCK',
  GET_PRODUCTS_REPORT_ORDERS: 'GET_PRODUCTS_REPORT_ORDERS',
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  DESTROY_PRODUCT: 'DESTROY_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  SET_PRODUCT_PRICE_GROUP: 'SET_PRODUCT_PRICE_GROUP'
}

export const FOLDER_MODULE = {
  SET_FOLDERS: 'SET_FOLDERS',
  GET_FOLDERS: 'GET_FOLDERS',
  SET_FOLDER: 'SET_FOLDER',
  GET_FOLDER: 'GET_FOLDER',
  FOLDERS: 'FOLDERS',
  FOLDER: 'FOLDER',
  CREATE_FOLDER: 'CREATE_FOLDER',
  DESTROY_FOLDER: 'DESTROY_FOLDER',
  UPDATE_FOLDER: 'UPDATE_FOLDER',
  FOLDERS_WITHOUT_CHILDS: 'FOLDERS_WITHOUT_CHILDS'
}

export const CATALOG_MODULE = {
  CATALOG_STATS: 'CATALOG_STATS',
  UPDATE_CATALOG_STATS: 'CATAUPDATE_CATALOG_STATSLOG_STATS',
  CATALOG_EXPORT: 'CATALOG_EXPORT',
  CATALOG_IMPORT: 'CATALOG_IMPORT',
  GET_CATALOG_INFO: 'GET_CATALOG_INFO',
  SET_CATALOG_INFO: 'SET_CATALOG_INFO'
}

export const CURRENCY_MODULE = {
  SET_CURRENCIES: 'SET_CURRENCIES',
  GET_CURRENCIES: 'GET_CURRENCIES',
  SET_CURRENCY: 'SET_CURRENCY',
  GET_CURRENCY: 'GET_CURRENCY',
  CURRENCIES: 'CURRENCIES',
  CURRENCY: 'CURRENCY',
  CREATE_CURRENCY: 'CREATE_CURRENCY',
  DESTROY_CURRENCY: 'DESTROY_CURRENCY',
  UPDATE_CURRENCY: 'UPDATE_CURRENCY'
}

export const PRICE_GROUP_MODULE = {
  SET_PRICE_GROUPS: 'SET_PRICE_GROUPS',
  GET_PRICE_GROUPS: 'GET_PRICE_GROUPS',
  SET_PRICE_GROUP: 'SET_PRICE_GROUP',
  GET_PRICE_GROUP: 'GET_PRICE_GROUP',
  PRICE_GROUPS: 'PRICE_GROUPS',
  PRICE_GROUP: 'PRICE_GROUP',
  CREATE_PRICE_GROUP: 'CREATE_PRICE_GROUP',
  DESTROY_PRICE_GROUP: 'DESTROY_PRICE_GROUP',
  UPDATE_PRICE_GROUP: 'UPDATE_PRICE_GROUP'
}

export const TRADEMARK_MODULE = {
  SET_TRADEMARKS: 'SET_TRADEMARKS',
  GET_TRADEMARKS: 'GET_TRADEMARKS',
  SET_TRADEMARK: 'SET_TRADEMARK',
  GET_TRADEMARK: 'GET_TRADEMARK',
  TRADEMARKS: 'TRADEMARKS',
  TRADEMARK: 'TRADEMARK',
  CREATE_TRADEMARK: 'CREATE_TRADEMARK',
  DESTROY_TRADEMARK: 'DESTROY_TRADEMARK',
  UPDATE_TRADEMARK: 'UPDATE_TRADEMARK'
}

export const ATTRIBUTE_MODULE = {
  SET_ATTRIBUTES: 'SET_ATTRIBUTES',
  GET_ATTRIBUTES: 'GET_ATTRIBUTES',
  SET_ATTRIBUTE: 'SET_ATTRIBUTE',
  GET_ATTRIBUTE: 'GET_ATTRIBUTE',
  ATTRIBUTES: 'ATTRIBUTES',
  ATTRIBUTE: 'ATTRIBUTE',
  CREATE_ATTRIBUTE: 'CREATE_ATTRIBUTE',
  CREATE_ATTRIBUTE_VALUE: 'CREATE_ATTRIBUTE_VALUE',
  UPDATE_ATTRIBUTE_VALUE: 'UPDATE_ATTRIBUTE_VALUE',
  DESTROY_ATTRIBUTE_VALUE: 'DESTROY_ATTRIBUTE_VALUE',
  UPDATE_ATTRIBUTE: 'UPDATE_ATTRIBUTE',
  DESTROY_ATTRIBUTE: 'DESTROY_ATTRIBUTE',
  DESTROY_PRODUCT_ATTRIBUTE: 'DESTROY_PRODUCT_ATTRIBUTE',
  ADD_PRODUCT_ATTRIBUTE: 'ADD_PRODUCT_ATTRIBUTE'
}

export const IMAGE_MODULE = {
  UPLOAD_IMAGES: 'UPLOAD_IMAGES',
  DESTROY_IMAGE: 'DESTROY_IMAGE',
  SORT_IMAGES: 'SORT_IMAGES'
}

export const STOCK_MODULE = {
  SET_STOCKS: 'SET_STOCKS',
  GET_STOCKS: 'GET_STOCKS',
  SET_STOCK: 'SET_STOCK',
  GET_STOCK: 'GET_STOCK',
  STOCKS: 'STOCKS',
  STOCK: 'STOCK',
  STOCK_STATS: 'STOCK_STATS',
  UPDATE_STOCK_STATS: 'UPDATE_STOCK_STATS',
  UPDATE_STOCK: 'UPDATE_STOCK',
  DESTROY_STOCK: 'DESTROY_STOCK',
  SET_STOCK_CATALOGS: 'SET_STOCK_CATALOGS',
  GET_STOCK_CATALOGS: 'GET_STOCK_CATALOGS',
  ROOT_FOLDERS: 'ROOT_FOLDERS',
  UPDATE_STOCK_CATALOGS: 'UPDATE_STOCK_CATALOGS'
}

export const STOCK_ACTION_MODULE = {
  SET_STOCK_ACTIONS: 'SET_STOCK_ACTIONS',
  GET_STOCK_ACTIONS: 'GET_STOCK_ACTIONS',
  SET_STOCK_ACTION: 'SET_STOCK_ACTION',
  GET_STOCK_ACTION: 'GET_STOCK_ACTION',
  STOCK_ACTIONS: 'STOCK_ACTIONS',
  STOCK_ACTION: 'STOCK_ACTION',
  CREATE_STOCK_ACTION: 'CREATE_STOCK_ACTION',
  UPDATE_STOCK_ACTION: 'UPDATE_STOCK_ACTION',
  SUBMIT_STOCK_ACTION: 'SUBMIT_STOCK_ACTION',
  DESTROY_STOCK_ACTION: 'DESTROY_STOCK_ACTION',
  CREATE_STOCK_PRODUCTS: 'CREATE_STOCK_PRODUCTS',
  STOCK_PRODUCTS: 'STOCK_PRODUCTS',
  SET_STOCK_PRODUCTS: 'SET_STOCK_PRODUCTS',
  CLEAR_STOCK_PRODUCTS: 'CLEAR_STOCK_PRODUCTS',
  DESTROY_STOCK_PRODUCT: 'DESTROY_STOCK_PRODUCT'
}

export const BILL_MODULE = {
  SET_BILLS: 'SET_BILLS',
  GET_BILLS: 'GET_BILLS',
  SET_BILL: 'SET_BILL',
  GET_BILL: 'GET_BILL',
  BILLS: 'BILLS',
  BILL: 'BILL',
  CREATE_BILL: 'CREATE_BILL',
  DESTROY_BILL: 'DESTROY_BILL',
  UPDATE_BILL: 'UPDATE_BILL',
  INCREMENT_BILL_COUNT: 'INCREMENT_BILL_COUNT',
  DECREMENT_BILL_COUNT: 'DECREMENT_BILL_COUNT'
}

export const PAYMENT_CATEGORY_MODULE = {
  SET_PAYMENT_CATEGORIES: 'SET_PAYMENT_CATEGORIES',
  GET_PAYMENT_CATEGORIES: 'GET_PAYMENT_CATEGORIES',
  SET_PAYMENT_CATEGORY: 'SET_PAYMENT_CATEGORY',
  GET_PAYMENT_CATEGORY: 'GET_PAYMENT_CATEGORY',
  PAYMENT_CATEGORIES: 'PAYMENT_CATEGORIES',
  PAYMENT_CATEGORY: 'PAYMENT_CATEGORY',
  CREATE_PAYMENT_CATEGORY: 'CREATE_PAYMENT_CATEGORY',
  DESTROY_PAYMENT_CATEGORY: 'DESTROY_PAYMENT_CATEGORY',
  UPDATE_PAYMENT_CATEGORY: 'UPDATE_PAYMENT_CATEGORY',
  INCOME_PAYMENT_CATEGORIES: 'INCOME_PAYMENT_CATEGORIES',
  OUTCOME_PAYMENT_CATEGORIES: 'OUTCOME_PAYMENT_CATEGORIES'
}

export const PAYMENT_STATE_MODULE = {
  SET_PAYMENT_STATES: 'SET_PAYMENT_STATES',
  GET_PAYMENT_STATES: 'GET_PAYMENT_STATES',
  SET_PAYMENT_STATE: 'SET_PAYMENT_STATE',
  GET_PAYMENT_STATE: 'GET_PAYMENT_STATE',
  PAYMENT_STATES: 'PAYMENT_STATES',
  PAYMENT_STATE: 'PAYMENT_STATE',
  GET_PAYMENT_STATES_REPORT: 'GET_PAYMENT_STATES_REPORT',
  CREATE_PAYMENT_STATE: 'CREATE_PAYMENT_STATE',
  DESTROY_PAYMENT_STATE: 'DESTROY_PAYMENT_STATE',
  UPDATE_PAYMENT_STATE: 'UPDATE_PAYMENT_STATE',
  INCOME_PAYMENT_STATES: 'INCOME_PAYMENT_STATES',
  OUTCOME_PAYMENT_STATES: 'OUTCOME_PAYMENT_STATES'
}

export const PAYMENT_MODULE = {
  SET_PAYMENTS: 'SET_PAYMENTS',
  GET_PAYMENTS: 'GET_PAYMENTS',
  SET_PAYMENT: 'SET_PAYMENT',
  GET_PAYMENT: 'GET_PAYMENT',
  GET_PAYMENTS_INFO: 'GET_PAYMENTS_INFO',
  SET_PAYMENTS_INFO: 'SET_PAYMENTS_INFO',
  PAYMENTS: 'PAYMENTS',
  PAYMENT: 'PAYMENT',
  PAYMENTS_STATS: 'PAYMENTS_STATS',
  GET_PAYMENTS_REPORT: 'GET_PAYMENTS_REPORT',
  CREATE_PAYMENT: 'CREATE_PAYMENT',
  DESTROY_PAYMENT: 'DESTROY_PAYMENT',
  UPDATE_PAYMENT: 'UPDATE_PAYMENT',
  IS_PAYMENT_FETCHED: 'IS_PAYMENT_FETCHED',
  CREATE_PAYMENT_INFO: 'CREATE_PAYMENT_INFO'
}

export const NP_MODULE = {
  SET_CITIES: 'SET_CITIES',
  GET_CITIES: 'GET_CITIES',
  CREATE_TNN_FORM: 'CREATE_TNN_FORM',
  CITIES: 'CITIES',
  GET_WAREHOUSES_BY_CODE: 'GET_WAREHOUSES_BY_CODE',
  WAREHOUSES: 'WAREHOUSES',
  SET_SENDERS: 'SET_SENDERS',
  GET_SENDERS: 'GET_SENDERS',
  SENDERS: 'SENDERS',
  CREATE_TTN: 'CREATE_TTN',
  GET_TTNS: 'GET_TTNS'
}

export const ORDER_MODULE = {
  SET_ORDERS: 'SET_ORDERS',
  GET_ORDERS: 'GET_ORDERS',
  SET_ORDER: 'SET_ORDER',
  GET_ORDER: 'GET_ORDER',
  ORDERS: 'ORDERS',
  ORDER: 'ORDER',
  GET_ORDERS_REPORT: 'GET_ORDERS_REPORT',
  CREATE_ORDER: 'CREATE_ORDER',
  CREATE_ORDER_INFO: 'CREATE_ORDER_INFO',
  SET_ORDERS_INFO: 'SET_ORDERS_INFO',
  GET_ORDERS_INFO: 'GET_ORDERS_INFO',
  ORDERS_STATS: 'ORDERS_STATS',
  DELIVERIES: 'DELIVERIES',
  PAYMENT_TYPES: 'PAYMENT_TYPES',
  PAYMENT_CHANNELS: 'PAYMENT_CHANNELS',
  SET_PAYMENT_CHANNELS: 'SET_PAYMENT_CHANNELS',
  SET_PAYMENT_TYPES: 'SET_PAYMENT_TYPES',
  SET_DELIVERIES: 'SET_DELIVERIES',
  UPDATE_ORDER_FIELD: 'UPDATE_ORDER_FIELD',
  ADD_ORDER_PRODUCTS: 'ADD_ORDER_PRODUCTS',
  DESTROY_ORDER_PRODUCT: 'DESTROY_ORDER_PRODUCT',
  UPDATE_ORDER_PRODUCT: 'UPDATE_ORDER_PRODUCT',
  UPDATE_ORDER_STATUS: 'UPDATE_ORDER_STATUS',
  SET_ORDER_STATUSES: 'SET_ORDER_STATUSES',
  ORDER_STATUSES: 'ORDER_STATUSES',
  ORDERS_PAYMENT_STATS: 'ORDERS_PAYMENT_STATS',
  CLEAR_ORDERS_SEARCH: 'CLEAR_ORDERS_SEARCH',
  SET_ORDERS_SEARCH: 'SET_ORDERS_SEARCH',
  GET_ORDERS_SEARCH: 'GET_ORDERS_SEARCH',
  ORDERS_SEARCH: 'ORDERS_SEARCH',
  GET_ORDER_CHART_INFO: 'GET_ORDER_CHART_INFO',
  SET_ORDER_TTN: 'SET_ORDER_TTN',
  SET_NP_ENABLE: 'SET_NP_ENABLE',
  NP_ENABLED: 'NP_ENABLED',
  SET_ORDER_KEY: 'SET_ORDER_KEY'
}

export const USER_MODULE = {
  SET_USER: 'SET_USER',
  GET_USER: 'GET_USER',
  SET_USERS: 'SET_USERS',
  GET_USERS: 'GET_USERS',
  USERS: 'USERS',
  USER: 'USER',
  AUTH: 'AUTH',
  LOGOUT: 'LOGOUT',
  CREATE_USER: 'CREATE_USER',
  DESTROY_USER: 'DESTROY_USER',
  RESTORE_USER: 'RESTORE_USER',
  EDITED_USER: 'EDITED_USER',
  SET_EDITED_USER: 'SET_EDITED_USER',
  GET_EDITED_USER: 'GET_EDITED_USER',
  UPDATE_EDITED_USER: 'UPDATE_EDITED_USER',
  UPDATE_EDITED_USER_PASSWORD: 'UPDATE_EDITED_USER_PASSWORD',
  UNSET_USER_IMAGE: 'UNSET_USER_IMAGE',
  SET_USER_IMAGE: 'SET_USER_IMAGE',
  GET_ROLES_INFO: 'GET_ROLES_INFO',
  SET_USER_ROLE: 'SET_USER_ROLE'
}

export const MODULES_MODULE = {
  SET_MODULES: 'SET_MODULES',
  GET_MODULES: 'GET_MODULES',
  ALL_MODULES: 'ALL_MODULES',
  MODULES: 'MODULES',
  SET_ALL_MODULES: 'SET_ALL_MODULES',
  IS_MODULES_LOADED: 'IS_MODULES_LOADED'
}

export const CLIENT_MODULE = {
  SET_CLIENTS: 'SET_CLIENTS',
  GET_CLIENTS: 'GET_CLIENTS',
  SET_CLIENT: 'SET_CLIENT',
  GET_CLIENT: 'GET_CLIENT',
  CLIENTS: 'CLIENTS',
  CLIENT: 'CLIENT'
}

export const IS_SIDEBAR_OPEN = 'IS_SIDEBAR_OPEN'
export const SET_SIDEBAR_STATE = 'SET_SIDEBAR_STATE'

export const PLUGIN_MODULE = {
  SET_PLUGINS: 'SET_PLUGINS',
  GET_PLUGINS: 'GET_PLUGINS',
  SET_PLUGIN: 'SET_PLUGIN',
  GET_PLUGIN: 'GET_PLUGIN',
  PLUGINS: 'PLUGINS',
  PLUGIN: 'PLUGIN',
  CREATE_PLUGIN: 'CREATE_PLUGIN',
  DESTROY_PLUGIN: 'DESTROY_PLUGIN',
  UPDATE_PLUGIN: 'UPDATE_PLUGIN',
  SET_PLUGIN_STATE: 'SET_PLUGIN_STATE'
}
